name: NoClip-OG
author: NotAlexNoyle
description: A Spigot plugin that allows you to phase through solid blocks like in Portal 2's console mode!
website: https://github.com/NotAlexNoyle/NoClip-OG
version: 1.1
api-version: 1.19
main: plugin.NoClip

commands:
  noclip:
    description: Phase through blocks like in Portal 2!
    aliases: [nc]
    
permissions:
  noclip.use:
    description: Permission to phase through blocks.
    default: op
